/* 1. List the number of films per category. */
USE sakila;


SELECT name, number
FROM category
INNER JOIN(

			SELECT count(film_id ) as number, category_id
			FROM film_category
			GROUP BY category_id) as t
ON category.category_id = t.category_id
ORDER BY number;

/* 2. Retrieve the store ID, city, and country for each store */


SELECT store_id, city, country
FROM country
INNER JOIN (
			SELECT store_id, city, country_id
			FROM city
			INNER JOIN (
						SELECT store_id, city_id
						FROM address
						INNER JOIN (
									SELECT store_id, address_id
									FROM  store) as s
						ON address.address_id = s.address_id) as t
			ON city.city_id = t.city_id) as b
ON country.country_id = b.country_id;

/* 3. Calculate the total revenue generated by each store in dollars. */


SELECT store_id, sum(amount) as total_revenue
FROM staff
INNER JOIN (
			SELECT amount, staff_id
			FROM payment) s
ON staff.staff_id = s.staff_id
GROUP BY store_id;

/* 4. Determine the average running time of films for each category. */

SELECT average_length, name
FROM category
INNER JOIN (
			SELECT avg(length) as average_length, category_id
			FROM film_category
			INNER JOIN(
						SELECT length, film_id
						FROM film) f
			ON film_category.film_id = f.film_id
			GROUP BY category_id) as t
ON category.category_id = t.category_id
ORDER BY average_length;


/* BONUS 

5. Identify the film categories with the longest average running time. 
(i choose top 3) */

SELECT average_length, name
FROM category
INNER JOIN (
			SELECT avg(length) as average_length, category_id
			FROM film_category
			INNER JOIN(
						SELECT length, film_id
						FROM film) f
			ON film_category.film_id = f.film_id
			GROUP BY category_id) as t
ON category.category_id = t.category_id
ORDER BY average_length DESC limit 3;

/* 6. Display the top 10 most frequently rented movies in descending order. */ 

SELECT title, counter
FROM film
INNER JOIN(
			SELECT film_id, count(rental_id) as counter
			FROM inventory
			INNER JOIN (

			SELECT rental_id, inventory_id
			FROM rental) t
			ON inventory.inventory_id = t.inventory_id
			GROUP BY film_id) f
ON film.film_id = f.film_id
ORDER BY counter DESC limit 10


