/* List the number of films per category. */

SELECT name, COUNT(*) AS films_per_category
FROM sakila.category
GROUP BY name;

/* Retrieve the store ID, city, and country for each store. */

SELECT store_id, address_id
FROM store;





/* Calculate the total revenue generated by each store in dollars. */

SELECT store_id, SUM(revenue) AS total_revenue
FROM stores
GROUP BY store_id;


/* Determine the average running time of films for each category. */

SELECT category.name AS name_of_category, AVG(film.length) AS average_running_time
FROM film
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON film_category.category_id = category.category_id
GROUP BY category.name;


/* Identify the film categories with the longest average running time. */

SELECT category.name AS name_of_category, AVG(length) AS average_running_time
FROM film
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON film_category.category_id = category.category_id
GROUP BY category.name
ORDER BY average_running_time DESC;


/*  Display the top 10 most frequently rented movies in descending order. */

SELECt title, COUNT(rental_id) AS rental_count
FROM film
JOIN rental ON film.film_id = rental.rental_id
GROUP BY film.title
ORDER BY rental_count DESC
LIMIT 10;

/* Determine if "Academy Dinosaur" can be rented from Store 1. */

SELECT title AS title_of_movie, store.store_id
FROM film
JOIN inventory ON film.film_id = inventory.film_id
JOIN store ON inventory.store_id = store.store_id
WHERE film.title = 'Academy Dinosaur'
AND store.store_id = 1;


