/*
Write SQL queries to perform the following tasks using the Sakila database:
    1. List the number of films per category.
    2. Retrieve the store ID, city, and country for each store.
    3. Calculate the total revenue generated by each store in dollars.
    4. Determine the average running time of films for each category.
    5. Identify the film categories with the longest average running time.
    6. Display the top 10 most frequently rented movies in descending order.
    7. Determine if "Academy Dinosaur" can be rented from Store 1.
*/
SELECT category_id, COUNT(*) AS number_films
FROM sakila.film_category
GROUP BY category_id;

-- SELECT *
-- FROM sakila.address;
-- SELECT city, country_id FROM sakila.city;
-- SELECT country, country_id FROM sakila.country;

CREATE TEMPORARY TABLE sakila.city_country
SELECT city.city_id, city.city, country.country
FROM sakila.city
INNER JOIN sakila.country
ON city.country_id = country.country_id;

SELECT store.store_id, address.address, city_country.city, city_country.country
FROM sakila.store
INNER JOIN sakila.address
ON store.address_id = address.address_id
INNER JOIN sakila.city_country
ON address.city_id = city_country.city_id;

SELECT store_id, SUM(amount) AS total_revenue_USD
FROM sakila.payment
INNER JOIN sakila.rental
ON payment.rental_id = rental.rental_id
INNER JOIN sakila.staff
ON rental.staff_id = staff.staff_id
GROUP BY store_id;

SELECT film_category.category_id AS film_category, AVG(film.length) as avg_duration
FROM sakila.film
INNER JOIN sakila.film_category
ON film.film_id = film_category.film_id
GROUP BY film_category.category_id
ORDER BY avg_duration DESC;

SELECT film.film_id, title, COUNT(*) AS times_rented
FROM sakila.rental
INNER JOIN sakila.inventory
ON rental.inventory_id = inventory.inventory_id
INNER JOIN sakila.film
ON inventory.film_id = film.film_id
GROUP BY film_id
ORDER BY times_rented DESC
LIMIT 10;

SELECT film.film_id, film.title, store_id
FROM sakila.film
INNER JOIN sakila.inventory
ON film.film_id = inventory.inventory_id
WHERE film.title = 'Academy Dinosaur';