/*Write SQL queries to perform the following tasks using the Sakila database:

Bonus:

Identify the film categories with the longest average running time.
Display the top 10 most frequently rented movies in descending order.
Determine if "Academy Dinosaur" can be rented from Store 1.
Provide a list of all distinct film titles, along with their availability status in the inventory. 
Include a column indicating whether each title is 'Available' or 'NOT available.' 
Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."
*/

#List the number of films per category.
SELECT COUNT(film_id) no_films, category_id
FROM film_category
GROUP BY category_id;

#Retrieve the store ID, city, and country for each store.
SELECT store_id, city.city_id, city.city,country
FROM store
INNER JOIN address
ON store.address_id=address.address_id
INNER JOIN city
ON address.city_id=city.city_id
INNER JOIN country
ON city.country_id=country.country_id;

#Calculate the total revenue generated by each store in dollars
SELECT COUNT(amount), store_id
FROM payment
INNER JOIN customer
ON payment.customer_id=customer.customer_id
GROUP BY store_id;

#Determine the average running time of films for each category.
SELECT AVG(length), category_id
FROM film
INNER JOIN film_category
ON film.film_id=film_category.film_id
GROUP BY category_id;







