use sakila;
show tables;

/*1.List the number of films per category.*/

select name, number_films
from category
inner join (
			select count(film_id) as number_films, category_id
			from film_category
			group by category_id) as f
on category.category_id = f.category_id;

/*2. Retrieve the store ID, city, and country for each store.*/

select store_id, city, country
from sakila.country
inner join (
			select city.city_id, city, country_id, store_id
			from sakila.city
			inner join (
						select store_id, address.address_id, city_id
						from sakila.store
						inner join sakila.address
						on sakila.store.address_id = sakila.address.address_id) as t
			on sakila.city.city_id = t.city_id) as f
on sakila.country.country_id = f.country_id;


/*3.  Calculate the total revenue generated by each store in dollars.*/

select *
from sakila.payment;

select store.store_id, sum(amount) as total_revenue
from sakila.store
inner join (
			select payment.staff_id, store_id, amount
			from sakila.payment
			inner join sakila.staff
			on payment.staff_id = staff.staff_id) as t
on store.store_id = t.store_id
group by store_id;


/*4.  Determine the average running time of films for each category.*/

select category.name, avg(length) as average_length
from sakila.category
inner join (
			select film_category.category_id, length
			from sakila.film
			inner join sakila.film_category
			on film.film_id = film_category.film_id) as t
on category.category_id = t.category_id
group by name
order by average_length desc;


