USE sakila; 
-- 1.List the number of films per category.

SELECT c.name, c.category_id, count(fc.film_id) AS 'number of films per category'
FROM film_category fc 
JOIN category c
USING(category_id)
GROUP BY c.category_id;


-- 2.Retrieve the store ID, city, and country for each store.

Select s.store_id, a.city_id, c.city, co.country 
FROM store s 
JOIN address a 
USING (address_id)
JOIN city c
USING (city_id) 
JOIN country co;

-- 3.Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, CONCAT("$", FORMAT(SUM(p.amount),2)) AS "Total revenue in dollars"
FROM staff s 
JOIN payment p 
USING(staff_id) 
GROUP BY s.store_id; 


-- 4.Determine the average running time of films for each category.

SELECT c.name, AVG(f.length) as 'Average length'
FROM film f
JOIN film_category fc 
USING(film_id)
JOIN category c 
USING (category_id) 
GROUP BY c.name;


-- 5.Identify the film categories with the longest average running time.

SELECT c.name, AVG(f.length) as 'Average length'
FROM film f
JOIN film_category fc 
USING(film_id)
JOIN category c 
USING (category_id) 
GROUP BY c.name
ORDER BY AVG(f.length) DESC LIMIT 3 ;

-- 6.Display the top 10 most frequently rented movies in descending order.

SELECT COUNT(r.rental_id), f.film_id, f.title
FROM rental r
JOIN inventory i 
USING(inventory_id) 
JOIN film f 
USING (film_id)
GROUP BY f.film_id 
ORDER BY COUNT(r.rental_id) DESC;


-- 7.Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT f.title, f.film_id, i.inventory_id, i.store_id
FROM film f
JOIN inventory i 
USING (film_id)
WHERE f.title = 'Academy Dinosaur'
AND i.store_id = 1;

-- Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be 
-- obtained using a CASE statement combined with IFNULL."

SELECT DISTINCT(f.title)
FROM film f
LEFT JOIN inventory i 
ON f.film_id = i.film_id;
