/* SQL JOINS LAB */

/* Challenge - Joining on multiple tables */

/* 1 List the number of films per category.*/
SELECT sakila.category.name, COUNT(film_category.category_id) AS number_of_films
FROM sakila.category
JOIN sakila.film_category ON sakila.category.category_id = sakila.film_category.category_id
GROUP BY sakila.category.name;

/* 2 Retrieve the store ID, city, and country for each store.*/
SELECT sakila.store.store_id, sakila.city.city, sakila.country.country
FROM sakila.store, sakila.address, sakila.city, sakila.country
WHERE sakila.store.address_id = sakila.address.address_id
  AND sakila.address.city_id = sakila.city.city_id
  AND sakila.city.country_id = sakila.country.country_id;

/* 3 Calculate the total revenue generated by each store in dollars.*/
SELECT sakila.store.store_id, SUM(payment.amount) AS total_revenue
FROM sakila.store
JOIN sakila.staff ON sakila.store.store_id = sakila.staff.store_id
JOIN sakila.payment ON sakila.staff.staff_id = sakila.payment.staff_id
GROUP BY sakila.store.store_id;


/* 4 Determine the average running time of films for each category.*/
SELECT category_id, AVG(film.length) 
FROM sakila.film
INNER JOIN sakila.film_category
ON sakila.film.film_id = sakila.film_category.film_id
GROUP BY category_id;

/* 5 Identify the film categories with the longest average running time.*/
SELECT category_id, AVG(film.length) AS avg_length
FROM sakila.film
INNER JOIN sakila.film_category
ON sakila.film.film_id = sakila.film_category.film_id
GROUP BY category_id
ORDER BY avg_length DESC;

/* 6 Display the top 10 most frequently rented movies in descending order.*/
SELECT film.title, COUNT(rental.rental_id) AS rental_count
FROM sakila.film
JOIN sakila.inventory ON sakila.film.film_id = sakila.inventory.film_id
JOIN sakila.rental ON sakila.inventory.inventory_id = sakila.rental.inventory_id
GROUP BY sakila.film.title
ORDER BY rental_count DESC
LIMIT 10;

/* 7 Determine if "Academy Dinosaur" can be rented from Store 1.*/
SELECT film.title, CASE WHEN COUNT(sakila.rental.rental_id) > 0 THEN 'Yes' ELSE 'No' END AS can_be_rented
FROM sakila.film
JOIN sakila.inventory ON sakila.film.film_id = sakila.inventory.film_id
JOIN sakila.rental ON sakila.inventory.inventory_id = sakila.rental.inventory_id
JOIN sakila.store ON sakila.inventory.store_id = sakila.store.store_id
WHERE sakila.film.title = 'Academy Dinosaur' AND sakila.store.store_id = 1;







